name: MarkBind Action

on:
  push:
    branches:
      - main # edit this to your main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Deploy MarkBind site
        uses: MarkBind/markbind-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          rootDirectory: './docs'
          baseUrl: '/ab3-docs-demo' # replace with your repo name
          version: '^5.0.2'
